In [18]:
import tensorflow as tf
import numpy as np
import time

In [20]:
x = tf.constant([1., 2., 3., 4., 5., 6., 7., 8., 9.], shape=[3, 3])
y = x  # この行を置き換えて確認します。

with tf.Session() as sess:
    print(sess.run(y))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# 1.自然対数 
$$
y = \log_{e} x
$$

In [21]:
x = tf.constant([1., 2., 3., 4., 5., 6., 7., 8., 9.], shape=[3, 3])
y = tf.log(x)

with tf.Session() as sess:
    print(sess.run(y))

[[0.        0.6931472 1.0986123]
 [1.3862944 1.609438  1.7917595]
 [1.9459102 2.0794415 2.1972246]]


# 2.総和
### $i$(1次元目)で足し合わせ
$$
y = \sum_{i=1}^{m}x_{ij}
$$

In [22]:
x = tf.constant([1., 2., 3., 4., 5., 6., 7., 8., 9.], shape=[3, 3])
# y = tf.reduce_sum(x,0)
y = tf.reduce_sum(x,reduction_indices=[0])

with tf.Session() as sess:
    print(sess.run(y))

[12. 15. 18.]


### $j$(2次元目)で足し合わせ
$$
y = \sum_{j=1}^{n}x_{ij}
$$

In [23]:
x = tf.constant([1., 2., 3., 4., 5., 6., 7., 8., 9.], shape=[3, 3])
# y = tf.reduce_sum(x,1)
y = tf.reduce_sum(x,reduction_indices=[1])

with tf.Session() as sess:
    print(sess.run(y))

[ 6. 15. 24.]


### すべての次元で足し合わせ
$$
y = \sum_{i=1}^{m}\sum_{j=1}^{n}x_{ij}
$$

In [24]:
x = tf.constant([1., 2., 3., 4., 5., 6., 7., 8., 9.], shape=[3, 3])
y = tf.reduce_sum(x)
with tf.Session() as sess:
    print(sess.run(y))

45.0


# 3.平均
### $i$(1次元目)の平均
$$
y = \frac{1}{m}\sum_{i=1}^{m}x_{ij}
$$

In [25]:
x = tf.constant([1., 2., 3., 4., 5., 6., 7., 8., 9.], shape=[3, 3])
# y = tf.reduce_mean(x,0)
y = tf.reduce_mean(x,reduction_indices=[0])
with tf.Session() as sess:
    print(sess.run(y))

[4. 5. 6.]


### $j$(2次元目)の平均
$$
y = \frac{1}{n}\sum_{j=1}^{n}x_{ij}
$$

In [26]:
x = tf.constant([1., 2., 3., 4., 5., 6., 7., 8., 9.], shape=[3, 3])
# y = tf.reduce_mean(x,1)
y = tf.reduce_mean(x,reduction_indices=[1])
with tf.Session() as sess:
    print(sess.run(y))

[2. 5. 8.]


### すべての次元の平均
$$
y = \frac{1}{mn}\sum_{i=1}^{m}\sum_{j=1}^{n}x_{ij}
$$

In [27]:
x = tf.constant([1., 2., 3., 4., 5., 6., 7., 8., 9.], shape=[3, 3])
y = tf.reduce_mean(x)
with tf.Session() as sess:
    print(sess.run(y))

5.0


## Session.run 和 Tensor.eval的区别

In [3]:
# 如果你有一个 Tensor t，在使用 t.eval() 时，它等价于 tf.get_default_session().run(t)

t = tf.constant(42.0)
sess = tf.Session()
with sess.as_default():   # or `with sess:` to close on exit
    assert sess is tf.get_default_session()
    assert t.eval() == sess.run(t)

In [6]:
# 区别在于，使用 sess.run() 在同一步获取多个tensor中的值

t = tf.constant(42.0)
u = tf.constant(37.0)
tu = tf.multiply(t, u)
ut = tf.multiply(u, t)
with sess.as_default():
   tu.eval()  # runs one step
   ut.eval()  # runs one step
   sess.run([tu, ut])  # evaluates both tensors in a single step

In [20]:
# 使用 tf.Session().run() 读取变量的值十分耗时

N = 1000
x = tf.constant([1.])
b = 1.

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer()) 

    t1 = time.time()
    for _ in range(N):
        y = sess.run(x)
    print '使用sess.run() 读取变量数据耗时', time.time()-t1

    t2 = time.time()
    for _ in range(N):
        a = b
    print '直接赋值耗时', time.time()-t2

使用sess.run() 读取变量数据耗时 0.101273059845
直接赋值耗时 0.000187873840332
