In [1]:
import tensorflow as tf
import numpy as np
import time

In [2]:
x = tf.constant([1., 2., 3., 4., 5., 6., 7., 8., 9.], shape=[3, 3])
y = x  # この行を置き換えて確認します。

with tf.Session() as sess:
    print(sess.run(y))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# 1.自然対数 
$$
y = \log_{e} x
$$

In [3]:
x = tf.constant([1., 2., 3., 4., 5., 6., 7., 8., 9.], shape=[3, 3])
y = tf.log(x)

with tf.Session() as sess:
    print(sess.run(y))

[[0.        0.6931472 1.0986123]
 [1.3862944 1.609438  1.7917595]
 [1.9459102 2.0794415 2.1972246]]


# 2.総和
### $i$(1次元目)で足し合わせ
$$
y = \sum_{i=1}^{m}x_{ij}
$$

In [4]:
x = tf.constant([1., 2., 3., 4., 5., 6., 7., 8., 9.], shape=[3, 3])
# y = tf.reduce_sum(x,0)
y = tf.reduce_sum(x,reduction_indices=[0])

with tf.Session() as sess:
    print(sess.run(y))

[12. 15. 18.]


### $j$(2次元目)で足し合わせ
$$
y = \sum_{j=1}^{n}x_{ij}
$$

In [5]:
x = tf.constant([1., 2., 3., 4., 5., 6., 7., 8., 9.], shape=[3, 3])
# y = tf.reduce_sum(x,1)
y = tf.reduce_sum(x,reduction_indices=[1])

with tf.Session() as sess:
    print(sess.run(y))

[ 6. 15. 24.]


### すべての次元で足し合わせ
$$
y = \sum_{i=1}^{m}\sum_{j=1}^{n}x_{ij}
$$

In [6]:
x = tf.constant([1., 2., 3., 4., 5., 6., 7., 8., 9.], shape=[3, 3])
y = tf.reduce_sum(x)
with tf.Session() as sess:
    print(sess.run(y))

45.0


# 3.平均
### $i$(1次元目)の平均
$$
y = \frac{1}{m}\sum_{i=1}^{m}x_{ij}
$$

In [7]:
x = tf.constant([1., 2., 3., 4., 5., 6., 7., 8., 9.], shape=[3, 3])
# y = tf.reduce_mean(x,0)
y = tf.reduce_mean(x,reduction_indices=[0])
with tf.Session() as sess:
    print(sess.run(y))

[4. 5. 6.]


### $j$(2次元目)の平均
$$
y = \frac{1}{n}\sum_{j=1}^{n}x_{ij}
$$

In [8]:
x = tf.constant([1., 2., 3., 4., 5., 6., 7., 8., 9.], shape=[3, 3])
# y = tf.reduce_mean(x,1)
y = tf.reduce_mean(x,reduction_indices=[1])
with tf.Session() as sess:
    print(sess.run(y))

[2. 5. 8.]


### すべての次元の平均
$$
y = \frac{1}{mn}\sum_{i=1}^{m}\sum_{j=1}^{n}x_{ij}
$$

In [9]:
x = tf.constant([1., 2., 3., 4., 5., 6., 7., 8., 9.], shape=[3, 3])
y = tf.reduce_mean(x)
with tf.Session() as sess:
    print(sess.run(y))

5.0
