In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn.feature_extraction.text import HashingVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from collections import Counter
import matplotlib.pyplot as plt
import pickle
from sklearn import metrics


In [2]:
np.set_printoptions(threshold=np.nan)
with open('data/Coordination_FA_id_to_lb.pickle', mode='rb') as f:
    id_to_code = pickle.load(f)
x = np.asarray([
    " ".join(i.strip().split()[2:])
    for i in open("data/Coordination_FA_edu_data.txt").readlines()
])
t = np.asarray(
    [
        l.strip().split()[:2]
        for l in open("data/Coordination_FA_edu_data.txt").readlines()
    ],
    dtype=np.int64)
train = np.arange(len(x)) % 10 != 0

print("train_x:", len(x[train]))
print("test_x", len(x[~train]))
print("train_y", len(t[train]))
print("test_y", len(t[~train]))

print("train_x[0]:", x[train][0])
print("train_y[0]:", t[train][0])
print("test_x[1]:", x[~train][1])
print("test_y[1]:", t[~train][1])


train_x: 3159
test_x 351
train_y 3159
test_y 351
train_x[0]: 18 20 3 1 0
train_y[0]: [4 4]
test_x[1]: 19 22 1 81 0
test_y[1]: [4 4]


In [3]:
c_vectorizer = CountVectorizer()
h_vectorizer = HashingVectorizer(non_negative=True, ngram_range=(1, 2), norm=u'l2')
# h_vectorizer = HashingVectorizer(ngram_range=(1, 2), norm=u'l2')
# h_vectorizer = HashingVectorizer()
dat = h_vectorizer.fit_transform(x.tolist())

train_feature = dat[train]
train_label = t[train][:,0]
test_feature = dat[~train]
test_label = t[~train][:,0]
class_names = list(id_to_code.values())

clf = svm.SVC(kernel='linear',probability=True)
clf.fit(train_feature,train_label)
test_pred = clf.predict(test_feature)
print("test_pred:",Counter(test_pred), " test_true:",Counter(test_label))
print("test acc =",metrics.accuracy_score(test_label, test_pred))
print("class:", class_names)
print(confusion_matrix(test_pred,test_label))
print(classification_report(test_pred,test_label, target_names=class_names))

/home/kinten/.pyenv/versions/3.5.5/lib/python3.5/site-packages/sklearn/feature_extraction/hashing.py:94: DeprecationWarning: the option non_negative=True has been deprecated in 0.19 and will be removed in version 0.21.
  " in version 0.21.", DeprecationWarning)
/home/kinten/.pyenv/versions/3.5.5/lib/python3.5/site-packages/sklearn/feature_extraction/hashing.py:94: DeprecationWarning: the option non_negative=True has been deprecated in 0.19 and will be removed in version 0.21.
  " in version 0.21.", DeprecationWarning)


test_pred: Counter({4: 263, 3: 70, 2: 16, 0: 2})  test_true: Counter({4: 242, 3: 82, 2: 20, 0: 4, 1: 2, 5: 1})
test acc = 0.8660968660968661
class: ['time management', 'task division', 'proceedings', 'technical coordination', 'blank', 'quote']
[[  1   0   0   0   1   0]
 [  0   0   0   0   0   0]
 [  0   0  12   1   3   0]
 [  0   2   3  59   6   0]
 [  3   0   5  22 232   1]
 [  0   0   0   0   0   0]]
                        precision    recall  f1-score   support

       time management       0.25      0.50      0.33         2
         task division       0.00      0.00      0.00         0
           proceedings       0.60      0.75      0.67        16
technical coordination       0.72      0.84      0.78        70
                 blank       0.96      0.88      0.92       263
                 quote       0.00      0.00      0.00         0

           avg / total       0.89      0.87      0.88       351



/home/kinten/.pyenv/versions/3.5.5/lib/python3.5/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [4]:
clf = svm.SVC(kernel='poly',probability=True)
clf.fit(train_feature,train_label)
test_pred = clf.predict(test_feature)
print("test_pred:",Counter(test_pred), " test_true:",Counter(test_label))
print("test acc =",metrics.accuracy_score(test_label, test_pred))
print("class:", class_names)
print(confusion_matrix(test_pred,test_label))
print(classification_report(test_pred,test_label, target_names=class_names))

test_pred: Counter({4: 351})  test_true: Counter({4: 242, 3: 82, 2: 20, 0: 4, 1: 2, 5: 1})
test acc = 0.6894586894586895
class: ['time management', 'task division', 'proceedings', 'technical coordination', 'blank', 'quote']
[[  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  4   2  20  82 242   1]
 [  0   0   0   0   0   0]]
                        precision    recall  f1-score   support

       time management       0.00      0.00      0.00         0
         task division       0.00      0.00      0.00         0
           proceedings       0.00      0.00      0.00         0
technical coordination       0.00      0.00      0.00         0
                 blank       1.00      0.69      0.82       351
                 quote       0.00      0.00      0.00         0

           avg / total       1.00      0.69      0.82       351



/home/kinten/.pyenv/versions/3.5.5/lib/python3.5/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [5]:
clf = svm.SVC(kernel='sigmoid',probability=True)
clf.fit(train_feature,train_label)
test_pred = clf.predict(test_feature)
print("test_pred:",Counter(test_pred), " test_true:",Counter(test_label))
print("test acc =",metrics.accuracy_score(test_label, test_pred))
print("class:", class_names)
print(confusion_matrix(test_pred,test_label))
print(classification_report(test_pred,test_label, target_names=class_names))

test_pred: Counter({4: 351})  test_true: Counter({4: 242, 3: 82, 2: 20, 0: 4, 1: 2, 5: 1})
test acc = 0.6894586894586895
class: ['time management', 'task division', 'proceedings', 'technical coordination', 'blank', 'quote']
[[  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  4   2  20  82 242   1]
 [  0   0   0   0   0   0]]
                        precision    recall  f1-score   support

       time management       0.00      0.00      0.00         0
         task division       0.00      0.00      0.00         0
           proceedings       0.00      0.00      0.00         0
technical coordination       0.00      0.00      0.00         0
                 blank       1.00      0.69      0.82       351
                 quote       0.00      0.00      0.00         0

           avg / total       1.00      0.69      0.82       351



/home/kinten/.pyenv/versions/3.5.5/lib/python3.5/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [6]:
clf = svm.SVC(kernel='rbf',probability=True)
clf.fit(train_feature,train_label)
test_pred = clf.predict(test_feature)
print("test_pred:",Counter(test_pred), " test_true:",Counter(test_label))
print("test acc =",metrics.accuracy_score(test_label, test_pred))
print("class:", class_names)
print(confusion_matrix(test_pred,test_label))
print(classification_report(test_pred,test_label, target_names=class_names))

test_pred: Counter({4: 351})  test_true: Counter({4: 242, 3: 82, 2: 20, 0: 4, 1: 2, 5: 1})
test acc = 0.6894586894586895
class: ['time management', 'task division', 'proceedings', 'technical coordination', 'blank', 'quote']
[[  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  4   2  20  82 242   1]
 [  0   0   0   0   0   0]]
                        precision    recall  f1-score   support

       time management       0.00      0.00      0.00         0
         task division       0.00      0.00      0.00         0
           proceedings       0.00      0.00      0.00         0
technical coordination       0.00      0.00      0.00         0
                 blank       1.00      0.69      0.82       351
                 quote       0.00      0.00      0.00         0

           avg / total       1.00      0.69      0.82       351



/home/kinten/.pyenv/versions/3.5.5/lib/python3.5/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [7]:
with open('data/Coordination_FA_id_to_lb.pickle', mode='rb') as f:
    id_to_code = pickle.load(f)

x = np.asarray(
    [" ".join(i.strip().split()[2:]) for i in open("data/Coordination_FA_edu_data.txt").readlines()])
t = np.asarray(
    [l.strip().split()[:2] for l in open("data/Coordination_FA_edu_data.txt").readlines()], dtype=np.int64)
train = np.arange(len(x)) % 10 != 0
print("traindata", len(x[train]))
print("test", len(x[~train]))
count_vectorizer = CountVectorizer()
vectorizer = HashingVectorizer(
    non_negative=True, ngram_range=(1, 2), norm=u'l2')
dat = vectorizer.fit_transform(x.tolist())

clf = svm.SVC(kernel='linear', probability=True)  #0.890063424947
#clf = svm.SVC(kernel='poly', probability=True) #0.547568710359
#clf = svm.SVC(kernel='sigmoid', probability=True) #0.547568710359
clf.fit(dat[train], t[train][:, 0])

pred = clf.predict(dat[~train])
label = t[~train][:, 0]
print(Counter(pred), Counter(label))
cf = confusion_matrix(pred, label)
print(cf)
#print(np.mean(label == pred))
class_names = list(id_to_code.values())
print(class_names)
print(classification_report(pred,label, target_names=class_names))

traindata 3159
test 351


/home/kinten/.pyenv/versions/3.5.5/lib/python3.5/site-packages/sklearn/feature_extraction/hashing.py:94: DeprecationWarning: the option non_negative=True has been deprecated in 0.19 and will be removed in version 0.21.
  " in version 0.21.", DeprecationWarning)
/home/kinten/.pyenv/versions/3.5.5/lib/python3.5/site-packages/sklearn/feature_extraction/hashing.py:94: DeprecationWarning: the option non_negative=True has been deprecated in 0.19 and will be removed in version 0.21.
  " in version 0.21.", DeprecationWarning)


Counter({4: 263, 3: 70, 2: 16, 0: 2}) Counter({4: 242, 3: 82, 2: 20, 0: 4, 1: 2, 5: 1})
[[  1   0   0   0   1   0]
 [  0   0   0   0   0   0]
 [  0   0  12   1   3   0]
 [  0   2   3  59   6   0]
 [  3   0   5  22 232   1]
 [  0   0   0   0   0   0]]
['time management', 'task division', 'proceedings', 'technical coordination', 'blank', 'quote']
                        precision    recall  f1-score   support

       time management       0.25      0.50      0.33         2
         task division       0.00      0.00      0.00         0
           proceedings       0.60      0.75      0.67        16
technical coordination       0.72      0.84      0.78        70
                 blank       0.96      0.88      0.92       263
                 quote       0.00      0.00      0.00         0

           avg / total       0.89      0.87      0.88       351



/home/kinten/.pyenv/versions/3.5.5/lib/python3.5/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
