In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn.feature_extraction.text import HashingVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from collections import Counter
import matplotlib.pyplot as plt
import pickle
from sklearn import metrics


In [2]:
np.set_printoptions(threshold=np.nan)
with open('data/Epistemic_FA_id_to_lb.pickle', mode='rb') as f:
    id_to_code = pickle.load(f)
x = np.asarray([
    " ".join(i.strip().split()[2:])
    for i in open("data/Epistemic_FA_edu_data.txt").readlines()
])
t = np.asarray(
    [
        l.strip().split()[:2]
        for l in open("data/Epistemic_FA_edu_data.txt").readlines()
    ],
    dtype=np.int64)
train = np.arange(len(x)) % 10 != 0

print(id_to_code)
print("train_x:", len(x[train]))
print("test_x", len(x[~train]))
print("train_y", len(t[train]))
print("test_y", len(t[~train]))

print("train_x[0]:", x[train][0])
print("train_y[0]:", t[train][0])
print("test_x[1]:", x[~train][1])
print("test_y[1]:", t[~train][1])


{0: 'on task', 1: 'off task'}
train_x: 7614
test_x 846
train_y 7614
test_y 846
train_x[0]: 41 36 12 7 0
train_y[0]: [1 1]
test_x[1]: 135 6 75 4 140 67 30 92 61 7 4 0
test_y[1]: [0 0]


In [3]:
c_vectorizer = CountVectorizer()
# h_vectorizer = HashingVectorizer(non_negative=True, ngram_range=(1, 2), norm=u'l2')
# h_vectorizer = HashingVectorizer(ngram_range=(1, 2), norm=u'l2')
h_vectorizer = HashingVectorizer()
dat = h_vectorizer.fit_transform(x.tolist())

train_feature = dat[train]
train_label = t[train][:,0]
test_feature = dat[~train]
test_label = t[~train][:,0]
class_names = list(id_to_code.values())

clf = svm.SVC(kernel='linear',probability=True)
clf.fit(train_feature,train_label)
test_pred = clf.predict(test_feature)
print("test_pred:",Counter(test_pred), " test_true:",Counter(test_label))
print("test acc =",metrics.accuracy_score(test_label, test_pred))
print("class:", class_names)
print(confusion_matrix(test_pred,test_label))
print(classification_report(test_pred,test_label, target_names=class_names))

test_pred: Counter({1: 462, 0: 384})  test_true: Counter({1: 456, 0: 390})
test acc = 0.9054373522458629
class: ['on task', 'off task']
[[347  37]
 [ 43 419]]
             precision    recall  f1-score   support

    on task       0.89      0.90      0.90       384
   off task       0.92      0.91      0.91       462

avg / total       0.91      0.91      0.91       846



In [4]:
clf = svm.SVC(kernel='poly',probability=True)
clf.fit(train_feature,train_label)
test_pred = clf.predict(test_feature)
print("test_pred:",Counter(test_pred), " test_true:",Counter(test_label))
print("test acc =",metrics.accuracy_score(test_label, test_pred))
print("class:", class_names)
print(confusion_matrix(test_pred,test_label))
print(classification_report(test_pred,test_label, target_names=class_names))

test_pred: Counter({1: 846})  test_true: Counter({1: 456, 0: 390})
test acc = 0.5390070921985816
class: ['on task', 'off task']
[[  0   0]
 [390 456]]
             precision    recall  f1-score   support

    on task       0.00      0.00      0.00         0
   off task       1.00      0.54      0.70       846

avg / total       1.00      0.54      0.70       846



/Users/kinten/.pyenv/versions/3.6.5/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [5]:
clf = svm.SVC(kernel='sigmoid',probability=True)
clf.fit(train_feature,train_label)
test_pred = clf.predict(test_feature)
print("test_pred:",Counter(test_pred), " test_true:",Counter(test_label))
print("test acc =",metrics.accuracy_score(test_label, test_pred))
print("class:", class_names)
print(confusion_matrix(test_pred,test_label))
print(classification_report(test_pred,test_label, target_names=class_names))

test_pred: Counter({1: 846})  test_true: Counter({1: 456, 0: 390})
test acc = 0.5390070921985816
class: ['on task', 'off task']
[[  0   0]
 [390 456]]
             precision    recall  f1-score   support

    on task       0.00      0.00      0.00         0
   off task       1.00      0.54      0.70       846

avg / total       1.00      0.54      0.70       846



/Users/kinten/.pyenv/versions/3.6.5/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [6]:
clf = svm.SVC(kernel='rbf',probability=True)
clf.fit(train_feature,train_label)
test_pred = clf.predict(test_feature)
print("test_pred:",Counter(test_pred), " test_true:",Counter(test_label))
print("test acc =",metrics.accuracy_score(test_label, test_pred))
print("class:", class_names)
print(confusion_matrix(test_pred,test_label))
print(classification_report(test_pred,test_label, target_names=class_names))

test_pred: Counter({1: 846})  test_true: Counter({1: 456, 0: 390})
test acc = 0.5390070921985816
class: ['on task', 'off task']
[[  0   0]
 [390 456]]
             precision    recall  f1-score   support

    on task       0.00      0.00      0.00         0
   off task       1.00      0.54      0.70       846

avg / total       1.00      0.54      0.70       846



/Users/kinten/.pyenv/versions/3.6.5/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [7]:
with open('data/Epistemic_FA_id_to_lb.pickle', mode='rb') as f:
    id_to_code = pickle.load(f)

x = np.asarray(
    [" ".join(i.strip().split()[2:]) for i in open("data/Epistemic_FA_edu_data.txt").readlines()])
t = np.asarray(
    [l.strip().split()[:2] for l in open("data/Epistemic_FA_edu_data.txt").readlines()], dtype=np.int64)
train = np.arange(len(x)) % 10 != 0
print("traindata", len(x[train]))
print("test", len(x[~train]))
count_vectorizer = CountVectorizer()
vectorizer = HashingVectorizer(
    non_negative=True, ngram_range=(1, 2), norm=u'l2')
dat = vectorizer.fit_transform(x.tolist())

clf = svm.SVC(kernel='linear', probability=True)  #0.890063424947
#clf = svm.SVC(kernel='poly', probability=True) #0.547568710359
#clf = svm.SVC(kernel='sigmoid', probability=True) #0.547568710359
clf.fit(dat[train], t[train][:, 0])

pred = clf.predict(dat[~train])
label = t[~train][:, 0]
print(Counter(pred), Counter(label))
cf = confusion_matrix(pred, label)
print(cf)
#print(np.mean(label == pred))
class_names = list(id_to_code.values())
print(class_names)
print(classification_report(pred,label, target_names=class_names))

traindata 7614
test 846


/Users/kinten/.pyenv/versions/3.6.5/lib/python3.6/site-packages/sklearn/feature_extraction/hashing.py:94: DeprecationWarning: the option non_negative=True has been deprecated in 0.19 and will be removed in version 0.21.
  " in version 0.21.", DeprecationWarning)
/Users/kinten/.pyenv/versions/3.6.5/lib/python3.6/site-packages/sklearn/feature_extraction/hashing.py:94: DeprecationWarning: the option non_negative=True has been deprecated in 0.19 and will be removed in version 0.21.
  " in version 0.21.", DeprecationWarning)


Counter({1: 459, 0: 387}) Counter({1: 456, 0: 390})
[[350  37]
 [ 40 419]]
['on task', 'off task']
             precision    recall  f1-score   support

    on task       0.90      0.90      0.90       387
   off task       0.92      0.91      0.92       459

avg / total       0.91      0.91      0.91       846

